source 'http://rubygems.org'

# load rhoconnect from relative path
gem 'rhoconnect', :path => '../../'

gemfile_path = File.join(File.dirname(__FILE__), '..', '..', 'generators','templates', 'application', "rcgemfile")
begin 
  eval(IO.read(gemfile_path)) 
rescue Exception => e
  puts "ERROR: Couldn't find RhoConnect .rcgemfile"
  puts e.message
  exit 1
end
